#ssh root@165.22.58.22
#MjMSWu7JJ+#9wN8s
# docker compose up -d mongodb mongodb1
version: "3.9"
services:
  mongodb:
    container_name: mongodb_container
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: testne
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
      # - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js

  mongodb1:
    container_name: mongodb_container_1
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: testne
    ports:
      - 27018:27018
    volumes:
      - mongodb_data_container_1:/data/db
      # - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js

networks:
  elastic:
    name: elastic
